### ISSUE TITLE
socket activation support

### ISSUE THREAD

**Issue by zabbal** [muelli/geysigning#17]
Would be nice to see socket activation support for the server side - this way it could be transparently restarted on upgrades without loosing client requests. Some helpful information could be found at http://gfxmonk.net/2012/05/15/systemd-socket-activation-in-python.html

**Comment by muelli** [comment]
I don't see how this is applicable. Currently, the user explicitly requests the server side to be started.
I doubt that we'll get into the situation in which the server side runs for a long time such that it will be upgraded while its running.  Am I missing anything here?

**Comment by zabbal** [comment]
Yes - socket activation removes the need to explicitly start server: it is started automatically only when it's actually needed for the client. One less thing for user to bother about.

**Comment by muelli** [comment]
I still don't see how this is relevant for this application. But it sounds cool and maybe I do when I see the patch.
