### ISSUE TITLE
Think of a new name for the project/repository

### ISSUE THREAD

**Issue by martinpaljak** [muelli/geysigning#24]
Not as bad as [pidora](http://www.themarysue.com/pidora-russian/), but guaranteed to raise eyebrows

**Comment by muelli** [comment]
Hi!  It's certainly not the name I want to keep. In fact, I'm always mentioning that the repository name will change once we've moved to GNOME infrastructure.  I envision "gnome-keysign". I hope that raises less eyebrows.

But am missing something glaringly obvious?  If it's about the "gey-signing" as in "gay signing", then I don't think immediate action is required. I'm not a native speaker of English (or most other languages FWIW...) so I am happy to learn new things and reassess the situation.

Thanks for your feedback!

**Comment by martinpaljak** [comment]
I don't remember you mentioning this yesterday, but maybe I just missed it (and thanks for the prsentation, I think yours and the fuzzing one were the most crowded ones).

**Comment by ccoenen** [comment]
what's wrong with the name?

**Comment by muelli** [comment]
We finally have a new repository: https://github.com/gnome-keysign/gnome-keysign  Let's move there.
