### ISSUE TITLE
Isolate calls to GnuPG and implement a pygpgme based wrapper

### ISSUE THREAD

**Issue by andreimacavei** [muelli/geysigning#29]
Currently, the library to call out to GnuPG used is coming from monkeysign. However, the industry standard seems to be pygpgme. In order to be able to replace the currently used wrapper with something based on pygpgme, the functionality required needs to be identified and isolated.

**Comment by boyska** [comment]
On this, I'd like to underline that this is not just about 'industry standard' but also about compatibility. Monkeysign does *not* work with gpg2 (which anyone should really switch to!), see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773970

**Comment by muelli** [comment]
I've sent patches to monkeysign to fix that particular problem. I can't find the archives right now, but it's in a message from March this year.

**Comment by muelli** [comment]
I guess this is being tracked as https://github.com/muelli/geysigning/pull/44
