### ISSUE TITLE
[GUI]: Disable signing the key if no valid key is entered

### ISSUE THREAD

**Issue by andreimacavei** [muelli/geysigning#31]
Right now this bug is allowing to advance into signing a key that is not valid or even if no key fingerprint is entered.

**Comment by muelli** [comment]
I don't understand this bug.  What exactly is the problem?

**Comment by andreimacavei** [comment]
This is a GUI bug. The 'Next' button should be disabled if you don't type/scan a fingerprint

**Comment by muelli** [comment]
right.  Spontaneously, I would say that by fixing https://github.com/muelli/geysigning/issues/27 this issue is solved as well.  Or am I missing anything?

**Comment by andreimacavei** [comment]
that's true indeed. I think I wanted to split issue #27 into two because it's more work to do the validation than just fixing some GUI issue. Anyway this can be done easily and it should be mentioned in #27 . Unfortunately I cannot delete it

**Comment by andreimacavei** [comment]
This should be fixed in #eab3d88

**Comment by muelli** [comment]
ah, cool.  Funny. I've cooked up 1c2140030f6d76e6a62ef409ee8c5ab5d44e9515
It seems to be almost the same.  Do you have a preference for either patch?

**Comment by andreimacavei** [comment]
I was thinking of using a switch_page() function to replace switching page and setting the progress bar (and do some processing on the error_fpr flag in the future, more explicitly, to put here the logic if app should advance or not). I will do another commit to use switch_page() call when pressing 'back' button also. Either commit is alright though.

**Comment by andreimacavei** [comment]
I think we can close this if you decided which patch are you going to use. I will go with your patch 1c21400 since it has less code.

**Comment by andreimacavei** [comment]
It was fixed in patch https://github.com/muelli/geysigning/commit/1c2140030f6d76e6a62ef409ee8c5ab5d44e9515
