### ISSUE TITLE
Gtk<3.6 compatibility: only call set_alway_show_image if available

### ISSUE THREAD

**Issue by NitikaAgarwal** [muelli/geysigning#4]
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
root (INFO): Startup
root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire' '--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode' '--no-tty' '--with-colons' '--use-agent' '--list-secret-keys'
Traceback (most recent call last):
  File "/home/nitika/geysigning/MainWindow.py", line 57, in on_startup
    notebook.append_page(KeySignSection(self), Gtk.Label('Keys'))
  File "/home/nitika/geysigning/Sections.py", line 212, in __init__
    self.backButton.set_always_show_image(True)
AttributeError: 'Button' object has no attribute 'set_always_show_image'
root (INFO): Activate!

**Comment by muelli** [comment]
should be fixed by 6bdb55aa8fe203fe1538165655e8fac0fa306e56
